[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Gabriel Birke <gabriel.birke@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
